_wandb:
    value:
        cli_version: 0.23.1
        e:
            wb9u8v0bkhdnpxbr5rog3t298oyld1sn:
                codePath: S2\mnist_cnn\S4\exercise_files\logger\train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "509722226688"
                        used: "344603172864"
                email: nico386d@gmail.com
                executable: C:\Users\nico3\miniforge3\envs\MLOP\python.exe
                git:
                    commit: 3ad82842c3699a787affc0c7ec5019abefdb6535
                    remote: https://github.com/nico386d/MLOP.git
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-95e2002b-af95-7324-0e2b-ada4d73647f9
                host: Nicolai
                memory:
                    total: "25463480320"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\nico3\MLOP\S2\mnist_cnn\S4\exercise_files\logger\train.py
                python: CPython 3.11.14
                root: C:\Users\nico3\MLOP\S2\mnist_cnn\S4\exercise_files\logger
                startedAt: "2026-01-07T11:00:44.346447Z"
                writerId: wb9u8v0bkhdnpxbr5rog3t298oyld1sn
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
